mysql:
  host: "127.0.0.1"
  port : 3306
  user: "root"
  password: "root"
  db: 'test'

redis:
  host: '127.0.0.1'
  port: 6379
  db: 2
  password: "123456"

watch_id : "watch_id"
author_id: "author_id"